language: csharp
solution: MathLibrary.sln
install:
    - nuget restore MathLibrary.sln
    - nuget install xunit.runners -Version 2.1.0 -OutputDirectory testrunner
script:
    - xbuild /p:Configuration=Release MathLibrary.sln
    - mono ./testrunner/xunit.runners.2.1.0/tools/xunit.console.exe ./MathLibrary/bin/Release/MathLibrary.dll 
