language: csharp
solution: MathLibrary.sln
install:
    - nuget restore MathLibrary.sln
    - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
    - xbuild /p:Configuration=Release MathLibrary.sln
    - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./MathLibrary/bin/Releae/MathLibrary.dll 